### ISSUE TITLE
not working with ST3?

### ISSUE THREAD

**Issue by geo4orce** [colinta/SublimeBracketeer#3]
I get the following error:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "bracketeer in /Volumes/MBUsers/Users/geo.artemenko/Library/Application Support/Sublime Text 3/Installed Packages/Bracketeer.sublime-package", line 376, in run
TypeError: begin_edit() missing 1 required positional argument: 'cmd'

Please help

**Comment by xianghongai** [comment]
Windows 10 18362，
ST 3211,

`Example.sublime-keymap`  `Bracket and select` command not working...

**Comment by colinta** [comment]
@xianghongai Usually it's better to open a new issue, rather than comment on a close one.  But in this case I won't be able to diagnose, I don't have a Windows computer to test on, and these commands work for me.  If you open a new issue, please include a lot more details on what "not working" means, i.e. include an example (text, what you expected, what happened), so I can at least try to reproduce it.  "Not working" is not a bug report, I can't investigate such a generic message.
